const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const GET_CREATIONS = "GET_CREATIONS"
const ADD_CREATION = "ADD_CREATION"
const EDIT_CREATION = "EDIT_CREATION"
const DELETE_CREATION = "DELETE_CREATION"
const SET_SELECTED_CREATION= "SET_SELECTED_CREATION"
const UNSET_CREATION = "UNSET_CREATION"
const COMMENT_FORM_CHANGE = "COMMENT_FORM_CHANGE"
const SET_COMMENT = "SET_COMMENT"
const EDIT_COMMENT = "EDIT_COMMENT"
const DELETE_COMMENT = "DELETE_COMMENT"
const FILTERS_FORM_CHANGE = "FILTERS_FORM_CHANGE"
const SET_FORM_DATA_FOR_EDIT_COMMENT = "SET_FORM_DATA_FOR_EDIT_COMMENT"
const RESET_FORM_DATA_FOR_EDIT_COMMENT = "RESET_FORM_DATA_FOR_EDIT_COMMENT"
const BEGIN_AUTH = "BEGIN_AUTH"
const COMPLETE_AUTH = "COMPLETE_AUTH"

export {
    SET_CURRENT_USER,
    CLEAR_CURRENT_USER,
    GET_CREATIONS,
    ADD_CREATION,
    EDIT_CREATION,
    DELETE_CREATION,
    SET_SELECTED_CREATION,
    UNSET_CREATION,
    COMMENT_FORM_CHANGE,
    SET_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT,
    FILTERS_FORM_CHANGE,
    SET_FORM_DATA_FOR_EDIT_COMMENT,
    RESET_FORM_DATA_FOR_EDIT_COMMENT,
    BEGIN_AUTH,
    COMPLETE_AUTH
}